######################################################################
# Automatically generated by qmake (3.0) Tue Sep 6 10:51:03 2016
######################################################################

TEMPLATE = app
TARGET = APCompSciA-CPP
INCLUDEPATH += .

# Input
SOURCES += main.cpp
